apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-control-plane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bhavesh1326/k8s-platform-local.git # Double-check your repo URL
    targetRevision: main
    path: istio/istio-control-plane
    helm:
      # This tells ArgoCD to use the official Istio Helm chart
      repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true